### ISSUE TITLE
expand list of permissible values for `location_category`

### ISSUE THREAD

**Issue by 08wparker** [clif-consortium/CLIF#26]

**Comment by 08wparker** [comment]
@ingra107 please sign off on this and then @kaveriC can add to data dictionary

**Comment by 08wparker** [comment]
add "map L&D to "Ward"" to the data dictionary instructions

**Comment by ingra107** [comment]
or do we want L&D as its own?  I have been mapping to other but i could do ward too if that's what we want

**Comment by cloverbunny** [comment]
I had mapped it to floor? Since they go to the OR if need C-section etc?I was thinking Other would be areas that are unclear, and we would drop from readmission analysis? What other things did you map to Other?Sent from iPhone; please excuse typos and brevity. On Oct 4, 2024, at 8:45 AM, Nick Ingraham ***@***.***> wrote:﻿
or do we want L&D as its own?  I have been mapping to other but i could do ward too if that's what we want

**Comment by 08wparker** [comment]
It will be very challenging to extract L&D from location_name and I suspect L&D population will be excluded from a lot of studies

**Comment by 08wparker** [comment]
Same goes for @sajor2000 comment about "inpatient hospice". 

So now the proposal is to to add "Stepdown","Labor and Delivery", and "Inpatient hospice" to the location_category list

**Comment by 08wparker** [comment]
The comment about nursing ratios and distinct nursing training being the guiding force for defining these levels makes sense to me

Observation units should be lumped with Ward because they are basically the same in most hospitals

**Comment by ingra107** [comment]
agreed about obs
L&D can be ward!

**Comment by cloverbunny** [comment]
Okay to clarify - sounds like we want to expand location_category options to include more details so list will look like
ICU 'icu'
Stepdown/intermediate care units 'stepdown' -> can be categorized into 'icu' or 'ward' by project-specific code 
Ward/observation/floor 'ward'
ED 'ed'
Procedural (IR, OR+PACU/Pre-Op areas, endoscopy) 'procedural'
Unknown locations and also MRI/CT etc (not associated with IR procedures) 'other'
L&D, mother/baby 'ob' (since may be excluded in some projects, but can be categorized into 'ward' etc by project-specific code) 
Hospice, LTACH, PT etc other locations -> 'other' as well since not technically in the hospital? 

Does that sound right? @sajor2000 @ingra107 @08wparker Any other grey areas we want to discuss as a group?

**Comment by 08wparker** [comment]
@cloverbunny @ingra107 @sajor2000 let's put this top of agenda on thursday. I think we should make `location_category` contain more levels because it's very difficult to figure out what the location is from `location_name` post-CLIF

**Comment by 08wparker** [comment]
The nice thing is that we are basically just breaking down our current "other" category further (ER, Procedural, ICU, Ward, Other)

**Comment by ingra107** [comment]
agree... the _name var is not as useful to getting ppl to nail down granularity through the _category var is best!

**Comment by cloverbunny** [comment]
ed,ward,stepdown,icu,procedural,l&d,other (example, hospice, rehab, xray, etc)
all lowercase!
Post questions here as they come up!

**Comment by cloverbunny** [comment]
Please everyone check for overlapping structure - for example UC had ICU start/stop time that had procedure start/stop time within that ICU location -> would want to break this up into ICU>procedure>ICU

Discussed at meeting today, no additional weird locations, closing out!
